/**
 * Error codes for SDK errors
 */
export enum ErrorCode {
    // General errors (1xx)
    UNKNOWN_ERROR = 100,
    INVALID_PARAMETER = 101,
    NOT_IMPLEMENTED = 102,
    TIMEOUT = 103,

    // Connection errors (2xx)
    CONNECTION_FAILED = 200,
    CONNECTION_IN_PROGRESS = 201,
    CONNECTION_LOST = 202,
    DISCONNECT_FAILED = 203,

    // Configuration errors (3xx)
    CONFIG_ERROR = 300,
    FILE_SYSTEM_ERROR = 301,

    // Session errors (4xx)
    SESSION_CREATION_FAILED = 400,
    SESSION_ALREADY_EXISTS = 401,
    SESSION_NOT_FOUND = 402,
    SESSION_NOT_READY = 403,
    SESSION_INVALID_STATE = 404,

    // Media errors (5xx)
    MEDIA_PIPELINE_ERROR = 500,
    MEDIA_CONNECTION_ERROR = 501,
    PIPELINE_NOT_READY = 502,
    PIPELINE_CREATION_FAILED = 503,
    PIPELINE_RELEASE_FAILED = 504,
    ELEMENT_CREATION_FAILED = 505,
    ENDPOINT_CREATION_FAILED = 506,
    ENDPOINT_NOT_READY = 507,
    ENDPOINT_RELEASE_ERROR = 508,

    // Recording errors (6xx)
    RECORDING_START_ERROR = 600,
    RECORDING_STOP_ERROR = 601,
    RECORDING_FILE_ERROR = 602,
    RECORDING_PAUSE_ERROR = 603,
    RESOURCE_RELEASE_ERROR = 604,

    // WebRTC errors (7xx)
    WEBRTC_OFFER_ERROR = 700,
    WEBRTC_ANSWER_ERROR = 701,
    WEBRTC_ICE_ERROR = 702,
    WEBRTC_CONNECTION_ERROR = 703
} 